---
# install apache
- name: Install apache
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-php5 state=present
    - php7.0-common
    - php7.0-cli
    - php7.0-dev
    - php7.0-fpm
    - libpcre3-dev
    - php7.0-gd
    - php7.0-curl
    - php7.0-imap
    - php7.0-json
    - php7.0-opcache
    - php7.0-xml
    - php7.0-mbstring
    - php-sqlite3
    - php-apcu



- name: copy application code to document root
  template: src=index.php.j2 dest=/var/www/html/now/index.php
  notify: restart apache